### PR TITLE
Support for ColorOctomapServer in rviz (indigo branch)

### PR DESCRIPTION
**Pull request by felixendres**
See description of pull request #17 and issue #13

### CODE REVIEW

**Comment by ahornung** [comment]
Would you mind adapting this change to the latest contribution in #16? (already merged, first come first served :wink: )

Basing this change on the templated plugin should also make this a bit more useful as it allows parallel plugins for different octree classes to coexist.

**Comment by felixendres** [comment]
Done. Will issue the pull request on Monday.

**Comment by felixendres** [comment]
Ok, this was the last commit. Now all the messages can be used in parallel without crashing rviz.

octree-type-messages

**Comment by ahornung** [comment]
Great, thanks a lot!

**Pull request merged**
