### PR TITLE
ROS2 Migration

### LINKED ISSUE #40: Release for foxy
Hello,

I'd like to ask if (and when) a release for ROS2 Foxy is planned. This plugin is very important for displaying and debugging our results of working with Octomap.

Thanks in advance!

### PR DESCRIPTION
**Pull request by wep21**
Close #40 
Screenshot from 2021-12-20 02-43-35

### CODE REVIEW

**Comment by wep21** [comment]
@wxmerkt I would appreciate it if you test the ros2 migration of rviz plugins with https://github.com/OctoMap/octomap_mapping/pull/95.

**Comment by wxmerkt** [comment]
@wep21 thank you very much for the work in upgrading this for ROS2. I am currently testing this locally with the other changes to `octomap_mapping`. Things are a bit delayed due to rendering issues in RViz2 on rolling and issues creating octomaps from OpenNI2 sensors. Will merge these as soon as I can get a working setup :-)

**Review by wxmerkt — APPROVED** [review]
Thank you very much for this effort @wep21. I've tested it and made a modification to make it run on Foxy as well.

**Comment by wxmerkt** [comment]
@cottsay - could you please create `octomap_rviz_plugins` and `octomap_mapping` release repositories in ros2-gbp? Many thanks and happy holidays :-)

**Comment by nuclearsandwich** [comment]
@wxmerkt https://github.com/ros2-gbp/octomap_rviz_plugins-release and https://github.com/ros2-gbp/octomap_mapping-release have been added to the octomap release team. In the future you can ping me directly for new repository requests as a quirk of our current deployment process means I'm always in the loop.

**Comment by wxmerkt** [comment]
Great, thank you for the super-swift action and note @nuclearsandwich - will do  :)

**Pull request merged**
